<?php
// $Id$

/**
 * @file
 */

function stormproject_help($path, $arg) {
  $o = '';

  switch ($path) {
    case "admin/help#stormproject":
      $o = '<p>'.  t("Provides project support for STORM") .'</p>';
      break;
  }

  return $o;
}

function stormproject_perm() {
  return array(
                'STORM project: access',
                'STORM project: add',
                'STORM project: delete all',
                'STORM project: delete own',
                'STORM project: edit all',
                'STORM project: edit own',
                'STORM project: view all',
                'STORM project: view own',
              );
}

function stormproject_init() {
  $settings = array(
                    'storm' => array(
                      'organization_projects_url' => url('storm/organization_projects_js/')
                    ),
              );
  drupal_add_js($settings, 'setting');

  drupal_add_js(drupal_get_path('module', 'storm') .'/storm.js', 'module', 'header', FALSE);
  drupal_add_js(drupal_get_path('module', 'stormproject') .'/stormproject.js', 'module', 'header', FALSE);
}

function stormproject_access($op, $node, $account) {
  if (is_numeric($node)) $node = node_load($node);

  if ($op == 'create') {
    return user_access('STORM project: add');
  }

  if ($op == 'delete') {
    if (user_access('STORM project: delete all')) {
      return TRUE;
    }
    else if (user_access('STORM project: delete own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }

  if ($op == 'update') {
    if (user_access('STORM project: edit all')) {
      return TRUE;
    }
    else if (user_access('STORM project: edit own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }

  if ($op == 'view') {
    if (user_access('STORM project: view all')) {
      return TRUE;
    }
    else if (user_access('STORM project: view own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
  return FALSE;
}

function stormproject_access_sql($sql, $where = array(), $join = array()) {

  if (user_access('STORM project: view all')) {
    return storm_rewrite_sql($sql, $where);
  }

  global $user;

  $cond = '';
  if (user_access('STORM project: view own')) {
    $cond .= 'n.uid='. $user->uid;
  }
  if (user_access('STORM project: view of user organization')) {
    if ($cond) $cond .= ' OR ';
    $cond .= 'spr.organization_nid='. $user->stormorganization_nid;
  }
  if (!$cond) {
    $cond = '0=1';
  }
  $where[] = $cond;

  return storm_rewrite_sql($sql, $where);
}

function stormproject_menu() {
  $items = array();

  $items['storm/projects'] = array(
    'title' => t('Projects'),
    'description' => t('STORM Projects'),
    'page callback' => 'stormproject_list',
    'access arguments' => array('STORM project: access'),
    'file' => 'stormproject.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  $items['storm/organization_projects_js/%'] = array(
    'title' => t('Projects'),
    'page callback' => '_stormproject_organization_projects_js',
    'page arguments' => array(2),
    'access arguments' => array('STORM project: access'),
    'file' => 'stormproject.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function stormproject_theme() {
  return array(
    'stormproject_list' => array(
      'file'      => 'stormproject.theme.inc',
      'arguments' => array('header', 'projects'),
    ),
    'stormproject_list_find' => array(
      'file'      => 'stormproject.theme.inc',
      'arguments' => array('form'),
    ),
  );
}

function stormproject_node_info() {
  return array(
    'stormproject' => array(
      'name' => t('Project'),
      'module' => 'stormproject',
      'description' => t("A project for STORM."),
      'title_label' => t("Title"),
      'body_label' => t("Description"),
    )
  );
}

function stormproject_storm_indexpage() {
  $o = array();
  if (user_access('STORM project: access')) {
    $o['stormproject']['title'] =  l(t('Projects'), 'storm/projects');
  }
  return $o;
}

function stormproject_stormorganization_change($organization_nid, $organization_title) {
  $s = "UPDATE {stormproject} SET organization_title='%s' WHERE organization_nid=%d AND organization_title <> '%s'";
  db_query($s, $organization_title, $organization_nid, $organization_title);
}

function stormproject_form(&$node) {
  if (arg(1)=='add') {
    if (array_key_exists('organization_nid', $_GET) && !$node->organization) {
      $node->organization_nid = $_GET['organization_nid'];
    }
    if ($_SESSION['stormproject_list_filter']['organization_nid'] && !$node->organization_nid) {
      $node->organization_nid = $_SESSION['stormproject_list_filter']['organization_nid'];
    }
  }

  $type = node_get_types('type', $node);

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -50,
  );

  $form['group1'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -49,
  );

  $s = "SELECT n.nid, n.title FROM {stormorganization} so INNER JOIN {node} n ON so.nid=n.nid WHERE n.status=1 AND n.type='stormorganization' ORDER BY n.title";
  $r = db_query(stormproject_access_sql($s));
  $organizations = array();
  while ($organization = db_fetch_object($r)) {
    $organizations[$organization->nid] = $organization->title;
    if (!$node->organization_nid) $node->organization_nid = $organization->nid;
  }
  $form['group1']['organization_nid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#options' => $organizations,
    '#default_value' => $node->organization_nid,
    '#process' => array('storm_dependent_select_process'),
  );

  $form['group1']['projectcategory'] = array(
    '#type' => 'select',
    '#title' => t('Category'),
    '#default_value' => $node->projectcategory,
    '#options' => stormattribute_attributes_bydomain('Project category'),
  );

  $form['group1']['projectstatus'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#default_value' => $node->projectstatus,
    '#options' => stormattribute_attributes_bydomain('Project status'),
  );

  $form['group2'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -48,
  );

  $form['group2']['pricemode'] = array(
    '#type' => 'select',
    '#title' => t('Price mode'),
    '#default_value' => $node->pricemode,
    '#options' => array('-' => '-') + stormattribute_attributes_bydomain('Price mode'),
  );

  $form['group2']['price'] = array(
    '#title' => 'Price',
    '#type' => 'textfield',
    '#size' => 15,
    '#default_value' => $node->price,
  );

  $form['group2']['currency'] = array(
    '#type' => 'select',
    '#title' => t('Price currency'),
    '#default_value' => $node->currency,
    '#options' => array('-' => '-') + stormattribute_attributes_bydomain('Currency'),
  );

  $form['body_filter']['#weight'] = -47;
  $form['body_filter']['body'] = array(
      '#type' => 'textarea',
      '#title' => check_plain($type->body_label),
      '#default_value' => $node->body,
      '#rows' => 20,
      '#required' => ($type->min_word_count > 0));
  $form['body_filter']['format'] = filter_form($node->format);

  $form['title_old'] = array(
    '#type' => 'hidden',
    '#default_value' => $node->title_old,
  );

  return $form;
}

function stormproject_insert($node) {
  $s = "SELECT title FROM {node} WHERE type='stormorganization' AND nid=%d";
  $r = db_query($s, $node->organization_nid);
  $o = db_fetch_object($r);

  db_query("INSERT INTO {stormproject}
          (vid, nid, organization_nid, organization_title, projectcategory, projectstatus, pricemode, price, currency)
          VALUES
          (%d, %d, %d, '%s', '%s', '%s', '%s', %f, '%s')",
          $node->vid, $node->nid, $node->organization_nid, $o->title, $node->projectcategory,
          $node->projectstatus, $node->pricemode, $node->price, $node->currency);
}

function stormproject_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    stormproject_insert($node);
  }
  else {
    $s = "SELECT title FROM {node} WHERE type='stormorganization' AND nid=%d";
    $r = db_query($s, $node->organization_nid);
    $o = db_fetch_object($r);

    db_query("UPDATE {stormproject} SET
        organization_nid=%d, organization_title='%s',
        projectcategory='%s', projectstatus='%s', pricemode='%s', price=%f, currency='%s' WHERE vid = %d",
        $node->organization_nid, $o->title, $node->projectcategory, $node->projectstatus,
        $node->pricemode, $node->price, $node->currency, $node->vid);
    if ($node->title != $node->title_old) {
      module_invoke_all('stormproject_change', $node->nid, $node->title);
    }
  }
}

function stormproject_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_query('DELETE FROM {stormproject} WHERE nid = %d', $node->nid);
}

function stormproject_load($node) {
  $additions = db_fetch_object(db_query('SELECT * FROM {stormproject} WHERE vid = %d', $node->vid));
  $additions->title_old = $node->title;
  return $additions;
}

function stormproject_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  $node->content['organization'] = array(
    '#value' => t('Organization') .' : '. l($node->organization_title, 'node/'. $node->organization_nid) .'<br />',
    '#weight' => 1,
  );
  $node->content['category'] = array(
    '#value' => t('Category') .' : '. $node->projectcategory .'<br />',
    '#weight' => 2,
  );
  $node->content['status'] = array(
    '#value' => t('Status') .' : '. $node->projectstatus .'<br />',
    '#weight' => 3,
  );

  if (module_exists('stormnote')) {
    $node->content['notes'] = array(
      '#value' => l(t('Notes'), 'storm/notes/', array('query' => array('project_nid' => $node->nid))) .'<br />',
      '#weight' => 4,
    );
  }

  if (module_exists('stormticket')) {
    $node->content['tickets'] = array(
      '#value' => l(t('Tickets'), 'storm/tickets/', array('query' => array('project_nid' => $node->nid))) .'<br />',
      '#weight' => 5,
    );
  }

  if (module_exists('stormtimetracking')) {
    $node->content['timetrackings'] = array(
      '#value' => l(t('Timetrackings'), 'storm/timetrackings/', array('query' => array('project_nid' => $node->nid))) .'<br />',
      '#weight' => 6,
    );
  }

  return $node;
}
