<?php

/**
 * @file
 */

function stormnote_help($path, $arg) {
  $o = '';

  switch ($path) {
    case "admin/help#stormnote":
      $o = '<p>'. t("Provides note support for Storm") .'</p>';
      break;
  }

  return $o;
}

function stormnote_permission() {
  return array(
    'Storm note: access' => array(
      'title' => t('Access Storm Note'),
    ),
    'Storm note: add' => array(
      'title' => t('Add Storm Notes'),
    ),
    'Storm note: delete all' => array(
      'title' => t('Delete Any Storm Note'),
    ),
    'Storm note: delete own' => array(
      'title' => t('Delete Authored Storm Notes'),
    ),
    'Storm note: delete of user organization' => array(
      'title' => t('Delete Storm Note in own Organization'),
    ),
    'Storm note: edit all' => array(
      'title' => t('Edit Any Storm Note'),
    ),
    'Storm note: edit own' => array(
      'title' => t('Edit Authored Storm Notes'),
    ),
    'Storm note: edit of user organization' => array(
      'title' => t('Edit Storm Notes in own Organization'),
    ),
    'Storm note: view all' => array(
      'title' => t('View Any Storm Note'),
    ),
    'Storm note: view own' => array(
      'title' => t('View Authored Storm Notes'),
    ),
    'Storm note: view of user organization' => array(
      'title' => t('View Storm Notes in own Organization'),
    ),
  );
}

function stormnote_access($op, $node, $account=NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  if ($op == 'create') {
    return user_access('Storm note: add');
  }

  if (is_numeric($node)) $node = node_load($node);

  if ($op == 'delete') {
    if (user_access('Storm note: delete all')) {
      return TRUE;
    }
    elseif (user_access('Storm note: delete own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm note: delete of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
  }

  if ($op == 'update') {
    if (user_access('Storm note: edit all')) {
      return TRUE;
    }
    elseif (user_access('Storm note: edit own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm note: edit of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
  }

  if ($op == 'view') {
    if (user_access('Storm note: view all')) {
      return TRUE;
    }
    elseif (user_access('Storm note: view own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm note: view of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
  }
  return FALSE;
}

function stormnote_access_sql($sql, $where = array()) {
  if (user_access('Storm note: view all')) {
    $where[] = "'storm_access'='storm_access'";
    return storm_rewrite_sql($sql, $where);
  }

  global $user;

  $cond = '';
  if (user_access('Storm note: view own')) {
    $cond .= 'n.uid='. $user->uid;
  }
  if (user_access('Storm note: view of user organization')) {
    if (!empty($cond)) $cond .= ' OR ';
    $cond .= 'sno.organization_nid='. $user->stormorganization_nid;
  }
  if (empty($cond)) $cond = '0=1';
  $where[] = $cond;

  $where[] = "'storm_access'='storm_access'";
  return storm_rewrite_sql($sql, $where);
}

function stormnote_storm_rewrite_where_sql($query, $primary_table, $account) {
  static $conds = array();

  if (isset($conds[$primary_table][$account->uid])) {
    return $conds[$primary_table][$account->uid];
  }

  if (preg_match("/'storm_access'='storm_access'/", $query)) {
    $cond = '';
  }
  else {
    if (user_access('Storm note: view all', $account)) {
      return '';
    }

    $cond = '';
    if (user_access('Storm note: view own', $account)) {
      $cond .= "${primary_table}.uid=". $account->uid;
    }
    if (user_access('Storm note: view of user organization', $account)) {
      if ($cond) {
        $cond .= ' OR ';
      }
      // If function is called without viewing a note, this variable may not be set.
      // These lines check for that and set the organization node id to zero if not otherwise set.
      if (!isset($account->stormorganization_nid)) {
        $account->stormorganization_nid = 0;
      }
      $cond .= ' sno1.organization_nid='. $account->stormorganization_nid;
    }
    if ($cond) {
      $cond = " WHEN 'stormnote' THEN (SELECT IF($cond,1,0) FROM {stormnote} sno1 WHERE sno1.vid=${primary_table}.vid) ";
    }
    else {
      $cond = " WHEN 'stormnote' THEN 0 ";
    }
  }

  $conds[$primary_table][$account->uid] = $cond;
  return $cond;
}

function stormnote_theme() {
  return array(
    'stormnote_view' => array(
      'file'      => 'stormnote.theme.inc',
      'variables' => array('node', 'view_mode'),
    ),
  );
}

function stormnote_node_info() {
  return array(
    'stormnote' => array(
      'name' => t('Note'),
      'base' => 'stormnote',
      'description' => t("A note for Storm."),
    )
  );
}

function stormnote_content_extra_fields($type_name) {
  if ($type_name == 'stormnote') {
    return array(
      'group1' => array('label' => 'Organization/Project/Task Group', 'weight' => -20),
    );
  }
}

function stormnote_stormorganization_change($organization_nid, $organization_title) {
  $s = "UPDATE {stormnote} SET organization_title='%s' WHERE organization_nid=%d AND organization_title <> '%s'";
  db_query($s, $organization_title, $organization_nid, $organization_title);
}

function stormnote_stormproject_change($project_nid, $project_title) {
  $s = "UPDATE {stormnote} SET project_title='%s' WHERE project_nid=%d AND project_title <> '%s'";
  db_query($s, $project_title, $project_nid, $project_title);
}

function stormnote_stormtask_change($task_nid, $task_title, $task_stepno) {
  $s = "UPDATE {stormnote} SET task_title='%s' WHERE task_nid=%d AND task_title<>'%s'";
  db_query($s, $task_title, $task_nid, $task_title);
}

function stormnote_stormproject_change_hierarchy($project_nid, $organization_nid, $organization_title) {
  $s = "UPDATE {stormnote} SET organization_nid=%d, organization_title='%s' WHERE project_nid=%d";
  db_query($s, $organization_nid, $organization_title, $project_nid);
}

function stormnote_stormtask_change_hierarchy($task_nid, $organization_nid, $organization_title, $project_nid, $project_title) {
  $s = "UPDATE {stormnote} SET organization_nid=%d, organization_title='%s', project_nid=%d, project_title='%s' WHERE task_nid=%d";
  db_query($s, $organization_nid, $organization_title, $project_nid, $project_title, $task_nid);
}

function stormnote_form(&$node, $form_state) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Storm'), 'storm');
  $breadcrumb[] = l(t('Notes'), 'storm/notes');
  drupal_set_breadcrumb($breadcrumb);

  if (arg(1)=='add') {
    if (array_key_exists('organization_nid', $_GET) && !$node->organization_nid) {
      $node->organization_nid = $_GET['organization_nid'];
    }
    if (array_key_exists('project_nid', $_GET) && !$node->project_nid) {
      $node->project_nid = $_GET['project_nid'];
      $p = node_load($node->project_nid);
      $node->organization_nid = $p->organization_nid;
      if (!stormorganization_access('view', $node->organization_nid)) {
        drupal_set_message(t("You cannot add a note for this project, as you do not have access to view the organization's profile"));
        drupal_goto('node/'. $node->project_nid);
      }
    }
    if (array_key_exists('task_nid', $_GET) && !$node->task_nid) {
      $node->task_nid = $_GET['task_nid'];
      $t = node_load($node->task_nid);
      $node->organization_nid = $t->organization_nid;
      $node->project_nid = $t->project_nid;
      // $project_access deals with the case whereby the project could be blank, hence access rules not required
      $project_access = $node->project_nid ? stormproject_access('view', $node->project_nid) : TRUE;
      if (!stormorganization_access('view', $node->organization_nid) || !stormproject_access('view', $node->project_nid)) {
        drupal_set_message(t("You cannot add a note for this task, as you do not have access to view the both the organization and project's profile"));
        drupal_goto('node/'. $node->task_nid);
      }
    }

    if (isset($_SESSION['stormnote_list_filter']['organization_nid']) && !$node->organization_nid) {
      $node->organization_nid = $_SESSION['stormnote_list_filter']['organization_nid'];
    }
    if (isset($_SESSION['stormnote_list_filter']['project_nid']) && !$node->project_nid) {
      $node->project_nid = $_SESSION['stormnote_list_filter']['project_nid'];
    }
    if (isset($_SESSION['stormnote_list_filter']['task_nid']) && !$node->task_nid) {
      $node->task_nid = $_SESSION['stormnote_list_filter']['task_nid'];
    }
  }

  $type = node_type_get_type($node);

  $form['group1'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group1') : -20,
  );

  $org_query = db_select('node', 'n');
  $org_query->join('stormorganization', 'sor', 'n.vid = sor.vid');
  $org_query
    ->fields('n', array('nid', 'title'))
    ->condition('n.status', 1)
    ->condition('n.type', 'stormorganization')
    ->condition('sor.isactive', 1)
    ->orderBy('n.title', 'ASC')
    ->addTag('node_access');

//  $s_org = stormorganization_access_sql($s_org);
  $org_result = $org_query->execute();
  $organizations = array();
  foreach ($org_result as $organization) {
    $organizations[$organization->nid] = $organization->title;
    if (!isset($node->organization_nid)) {
      $node->organization_nid = $organization->nid;
    }
  }
  $form['group1']['organization_nid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#default_value' => $node->organization_nid,
    '#options' => $organizations,
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => 'stormnote_ajax_organization_nid',
      'wrapper' => 'stormnote-project-nid',
    ),
  );

  $organization_nid = isset($form_state['values']['organization_nid']) ? $form_state['values']['organization_nid'] : $node->organization_nid;

  $pro_query = db_select('node', 'n');
  $pro_query->join('stormproject', 'spr', 'n.vid = spr.vid');
  $pro_result = $pro_query
    ->fields('n', array('nid', 'title'))
    ->condition('n.status', 1)
    ->condition('spr.organization_nid', $organization_nid)
    ->condition('n.type', 'stormproject')
    ->orderBy('n.title', 'ASC')
    ->addTag('node_access')
    ->execute();

  $projects = array();
  foreach ($pro_result as $project) {
    $projects[$project->nid] = $project->title;
  }

  $project_nid = isset($form_state['values']['project_nid']) ? $form_state['values']['project_nid'] : (isset($node->project_nid) ? $node->project_nid : NULL);

  $form['group1']['project_nid'] = array(
    '#type' => 'select',
    '#title' => t('Project'),
    '#default_value' => $project_nid,
    '#options' => array(0 => '-') + $projects,
    '#prefix' => '<div id="stormnote-project-nid">',
    '#suffix' => '</div>',
    '#ajax' => array(
      'callback' => 'stormnote_ajax_project_nid',
      'wrapper' => 'stormnote-task-nid',
    ),

  );

//  $tree = is_null($project_nid) ? array() : _stormtask_get_tree($project_nid);
//  $tasks = _stormtask_plain_tree($tree);
  $form['group1']['task_nid'] = array(
    '#type' => 'select',
    '#title' => t('Task'),
    '#default_value' => isset($node->task_nid) ? $node->task_nid : NULL,
    '#options' => array(0 => '-'),// + $tasks,
    '#prefix' => '<div id="stormtask-project-nid">',
    '#suffix' => '</div>',
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'title') : -16,
  );

  // Check to see if the body field is still there, if so, display it.
  $body = field_get_items('stormtask', $node, 'body');
  if ($body) {
    $form['body_field'] = $body;
  }

  return $form;
}

function stormnote_ajax_organization_nid(&$form, &$form_state) {
  return $form['group1']['project_nid'];
}

function stormnote_ajax_project_nid(&$form, &$form_state) {
  return $form['group1']['task_nid'];
}

function stormnote_insert($node) {
  _stormnote_beforesave($node);

  db_insert('stormnote')
    ->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      'organization_nid' => $node->organization_nid,
      'organization_title' => $node->organization_title,
      'project_nid' => $node->project_nid,
      'project_title' => $node->project_title,
      'task_nid' => $node->task_nid,
      'task_title' => $node->task_title,
    ))
    ->execute();
}

function stormnote_update($node) {
  _stormnote_beforesave($node);

  if ($node->revision) {
    stormnote_insert($node);
  }
  else {
    db_update('stormnote')
      ->fields(array(
        'organization_nid' => $node->organization_nid,
        'organization_title' => $node->organization_title,
        'project_nid' => $node->project_nid,
        'project_title' => $node->project_title,
        'task_nid' => $node->task_nid,
        'task_title' => $node->task_title,
      ))
      ->condition('vid', $node->vid)
      ->execute();
  }
}

function _stormnote_beforesave(&$node) {
  $org_result = db_select('node', 'n')
    ->fields('n', array('title'))
    ->condition('n.type', 'stormorganization')
    ->condition('n.nid', $node->organization_nid)
    ->execute();
  $organization = $org_result->fetchObject();
  $node->organization_title = $organization->title;

  $pro_result = db_select('node', 'n')
    ->fields('n', array('title'))
    ->condition('n.type', 'stormproject')
    ->condition('n.nid', $node->project_nid)
    ->execute();
  $project = $pro_result->fetchObject();
  $node->project_title = isset($project->title) ? $project->title : '';

  $task_result = db_select('node', 'n')
    ->fields('n', array('title'))
    ->condition('n.type', 'stormtask')
    ->condition('n.nid', $node->task_nid)
    ->execute();
  $task = $task_result->fetchObject();
  $node->task_title = isset($task->title) ? $task->title : '';
}

function stormnote_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'delete revision':
      // Notice that we're matching a single revision based on the node's vid.
      db_delete('stormnote')
        ->condition('vid', $node->vid)
        ->execute();
      break;
  }
}

function stormnote_delete($node) {
  db_delete('stormnote')
    ->condition('nid', $node->nid)
    ->execute();
}

function stormnote_load($nodes) {
  foreach ($nodes as $nid => &$node) {
    $result = db_select('stormnote', 'sno')
      ->fields('sno')
      ->condition('sno.vid', $node->vid)
      ->execute();
    $record = $result->fetchAssoc();

    foreach ($record as $key => $value) {
      $node->$key = $value;
    }

    $node->title_old = $node->title;
  }
}

function stormnote_view($node, $view_mode = 'full') {
  if ($view_mode = 'full') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Storm'), 'storm');
    $breadcrumb[] = l(t('Notes'), 'storm/notes');
    drupal_set_breadcrumb($breadcrumb);
  }

  return theme('stormnote_view', array('node' => $node, 'view_mode' => $view_mode));
}

function stormnote_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'stormnote'),
  );
}

function stormnote_storm_dashboard_links($type) {
  $links = array();
  if ($type == 'page' || $type == 'block') {
    $links[] = array(
      'theme' => 'storm_dashboard_link',
      'title' => t('Notes'),
      'icon' => 'stormnotes',
      'path' => 'storm/notes',
      'params' => array(),
      'access_arguments' => 'Storm note: access',
      'node_type' => 'stormnote',
      'add_type' => 'stormnote',
      'map' => array(),
      'weight' => 9,
    );
  }
  return $links;
}
