<?php

/**
 * @file
 */

function stormperson_help($path, $arg) {
  $o = '';

  switch ($path) {
    case "admin/help#stormperson":
      $o = '<p>'. t("Provides person support for Storm") .'</p>';
      break;
  }

  return $o;
}

function stormperson_init() {
  if (function_exists('drupal_set_content')) {
    global $user;
    if ($user->uid && !isset($user->stormorganization_nid) || !isset($user->stormperson_nid)) {
      _stormperson_user_load($user);
    }
    if (!$user->uid || !isset($user->stormperson_nid)) {
      $user->stormperson_nid = -1;
    }
    if (!$user->uid || !isset($user->stormorganization_nid)) {
      $user->stormorganization_nid = -1;
    }
  }

  $settings = array(
    'storm' => array(
      'organization_people_url' => url('storm/organization_people_js/')
    ),
  );
  drupal_add_js($settings, 'setting');
  drupal_add_js(drupal_get_path('module', 'storm') .'/storm.js', 'module', 'header', FALSE);
  drupal_add_js(drupal_get_path('module', 'stormperson') .'/stormperson.js', 'module', 'header', FALSE);
}

function stormperson_permission() {
  return array(
    'Storm person: access' => array(
      'title' => t('Access Storm Person'),
    ),
    'Storm person: add' => array(
      'title' => t('Add Storm Person'),
    ),
    'Storm person: delete all' => array(
      'title' => t('Delete Any Storm Person'),
    ),
    'Storm person: delete own' => array(
      'title' => t('Delete Authored Storm Person'),
    ),
    'Storm person: delete of user organization' => array(
      'title' => t('Delete Storm Persons in own Organization'),
    ),
    'Storm person: delete when linked to own user account' => array(
      'title' => t('Delete Storm Person linked to own user account'),
    ),
    'Storm person: edit all' => array(
      'title' => t('Edit Any Storm Person'),
    ),
    'Storm person: edit own' => array(
      'title' => t('Edit Authored Storm Person'),
    ),
    'Storm person: edit of user organization' => array(
      'title' => t('Edit Storm Persons in own Organization'),
    ),
    'Storm person: edit when linked to own user account' => array(
      'title' => t('Edit Storm Person linked to own user account'),
    ),
    'Storm person: view all' => array(
      'title' => t('View Any Storm Person'),
    ),
    'Storm person: view own' => array(
      'title' => t('View Authored Storm Person'),
    ),
    'Storm person: view of user organization' => array(
      'title' => t('View Storm Persons in own Organization'),
    ),
    'Storm person: view when linked to own user account' => array(
      'title' => t('View Storm Person linked to own user account'),
    ),
  );
}

function stormperson_access($op, $node, $account=NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  if (is_numeric($node)) $node = node_load($node);

  if ($op == 'create') {
    return user_access('Storm person: add');
  }

  if ($op == 'delete') {
    if (user_access('Storm person: delete all')) {
      return TRUE;
    }
    elseif (user_access('Storm person: delete own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: delete of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: delete when linked to own user account') && ($account->uid == $node->user_uid)) {
      return TRUE;
    }
  }

  if ($op == 'update') {
    if (user_access('Storm person: edit all')) {
      return TRUE;
    }
    elseif (user_access('Storm person: edit own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: edit of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: edit when linked to own user account') && ($account->uid == $node->user_uid)) {
      return TRUE;
    }
  }

  if ($op == 'view') {
    if (user_access('Storm person: view all')) {
      return TRUE;
    }
    elseif (user_access('Storm person: view own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: view of user organization') && ($account->stormorganization_nid == $node->organization_nid)) {
      return TRUE;
    }
    elseif (user_access('Storm person: view when linked to own user account') && ($account->uid == $node->user_uid)) {
      return TRUE;
    }
  }
  return FALSE;
}

function stormperson_access_sql($sql, $where = array()) {
  if (user_access('Storm person: view all')) {
    $where[] = "'storm_access'='storm_access'";
    return storm_rewrite_sql($sql, $where);
  }

  global $user;

  $cond = '';
  if (user_access('Storm person: view own')) {
    $cond .= 'n.uid='. $user->uid;
  }
  if (user_access('Storm person: view of user organization')) {
    if (!empty($cond)) $cond .= ' OR ';
    $cond .= 'spe.organization_nid='. $user->stormorganization_nid;
  }
  if (user_access('Storm person: view when linked to own user account')) {
    if (!empty($cond)) $cond .= ' OR ';
    $cond .= 'spe.user_uid='. $user->uid;
  }
  if (empty($cond)) $cond = '0=1';
  $where[] = $cond;

  $where[] = "'storm_access'='storm_access'";
  return storm_rewrite_sql($sql, $where);
}

function stormperson_storm_rewrite_where_sql($query, $primary_table, $account) {
  static $conds = array();

  if (isset($conds[$primary_table][$account->uid])) {
    return $conds[$primary_table][$account->uid];
  }

  if (preg_match("/'storm_access'='storm_access'/", $query)) {
    $cond = '';
  }
  else {
    if (user_access('Storm person: view all', $account)) {
      return '';
    }

    $cond = '';
    if (user_access('Storm person: view own', $account)) {
      $cond .= " ${primary_table}.uid=". $account->uid;
    }
    if (user_access('Storm person: view of user organization', $account)) {
      if ($cond) {
        $cond .= ' OR ';
      }
      // If function is called without viewing an organization, this variable may not be set.
      // These lines check for that and set the organization node id to zero if not otherwise set.
      if (!isset($account->stormorganization_nid)) {
        $account->stormorganization_nid = 0;
      }
      $cond .= ' spe1.organization_nid='. $account->stormorganization_nid;
    }
    if (user_access('Storm person: view when linked to own user account', $account)) {
      if ($cond) {
        $cond .= ' OR ';
      }
      $cond .= ' spe1.user_uid='. $account->uid;
    }

    if ($cond) {
      $cond = " WHEN 'stormperson' THEN (SELECT IF($cond,1,0) FROM {stormperson} spe1 WHERE spe1.vid=${primary_table}.vid) ";
    }
    else {
      $cond = " WHEN 'stormperson' THEN 0 ";
    }
  }

  $conds[$primary_table][$account->uid] = $cond;
  return $cond;
}

function stormperson_menu() {
  $items['storm/people'] = array(
    'title' => 'People',
    'description' => 'Storm people',
    'page callback' => 'stormperson_list',
    'access arguments' => array('Storm person: access'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'stormperson.admin.inc',
    'weight' => 1,
  );

  $items['storm/organization_people_js/%'] = array(
    'title' => 'People',
    'page callback' => '_stormperson_organization_people_js',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'stormperson.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['storm/stormperson_js'] = array(
    'title' => 'Stormperson - User autocomplete',
    'page callback' => 'stormperson_user_autocomplete',
    'access callback' => 'user_access',
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function stormperson_theme() {
  return array(
    'stormperson_list' => array(
      'file'      => 'stormperson.theme.inc',
      'variables' => array('header', 'people'),
    ),
    'stormperson_people' => array(
      'file'      => 'stormperson.theme.inc',
      'arguments' => array('header', 'people'),
    ),
    'stormperson_view' => array(
      'file'      => 'stormperson.theme.inc',
      'variables' => array('node', 'view_mode'),
    ),
  );
}

function stormperson_node_info() {
  return array(
    'stormperson' => array(
      'name' => t('Person'),
      'base' => 'stormperson',
      'description' => t("A person for Storm."),
      'title_label' => t("Name"),
      'body_label' => t("Description"),
    )
  );
}

function stormperson_content_extra_fields($type_name) {
  if ($type_name == 'stormperson') {
    return array(
      'group1' => array('label' => 'Prefix/Name Group', 'weight' => -20),
      'group2' => array('label' => 'Organization/User Group', 'weight' => -19),
      'group3' => array('label' => 'Email/WWW Group', 'weight' => -18),
      'group4' => array('label' => 'Phone/IM Group', 'weight' => -17),
    );
  }
}

function stormperson_stormorganization_change($organization_nid, $organization_title) {
  db_update('stormperson')
    ->fields(array('organization_title' => $organization_title))
    ->condition('organization_nid', $organization_nid)
    ->execute();
}

function stormperson_form(&$node) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Storm'), 'storm');
  $breadcrumb[] = l(t('People'), 'storm/people');
  drupal_set_breadcrumb($breadcrumb);

  if (arg(1)=='add') {
    if (array_key_exists('organization_nid', $_GET) && !$node->organization_nid) {
      $node->organization_nid = $_GET['organization_nid'];
    }

    if (isset($_SESSION['stormperson_list_filter']['organization_nid']) && !$node->organization_nid) {
      $node->organization_nid = $_SESSION['stormperson_list_filter']['organization_nid'];
    }
  }

  $type = node_type_get_type($node);

  $form['#attributes']['class'] = 'stormcomponent_node_form';

  $form['group1'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group1') : -20,
  );

  $form['group1']['prefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Prefix'),
    '#size' => 20,
    '#default_value' => isset($node->prefix) ? $node->prefix : '',
  );

  $form['group1']['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#size' => 40,
  );

  $form['group2'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group2') : -19,
  );

  $query = db_select('node', 'n');
  $query->join('stormorganization', 'sor', 'sor.vid = n.vid');
  $result = $query
    ->fields('n', array('nid', 'title'))
    ->condition('n.status', 1)
    ->condition('n.type', 'stormorganization')
    ->orderBy('n.title', 'ASC')
    ->execute();

//  $s = stormorganization_access_sql($s);
//  $s = db_rewrite_sql($s);
  $organizations = array();
  foreach ($result as $organization) {
    $organizations[$organization->nid] = $organization->title;
    if (!isset($node->organization_nid)) $node->organization_nid = $organization->nid;
  }
  if (empty($organizations)) {
    $message = t('Before you add a Person, you must first !link.', array('!link' => l('add an Organization', 'node/add/stormorganization')));
    drupal_set_message($message, 'error');
  }

  $form['group2']['organization_nid'] = array(
    '#type' => 'select',
    '#title' => t('Organization'),
    '#default_value' => isset($node->organization_nid) ? $node->organization_nid : NULL,
    '#options' => $organizations,
    '#required' => TRUE,
    '#attributes' => array('onchange' => "stormperson_organization_project_tasks(this, 'edit-project-nid', 'edit-parent-nid', true, '-')"),
  );

  $form['group2']['user_name'] = array(
    '#type' => 'textfield',
    '#title' => t('User'),
    '#default_value' => isset($node->user_name) ? $node->user_name : '',
    '#autocomplete_path' => 'storm/stormperson_js',
    '#size' => 40,
  );

  $form['group3'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group3') : -18,
  );

  $form['group3']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#size' => 30,
    '#default_value' => isset($node->email) ? $node->email : '',
  );

  $form['group3']['www'] = array(
    '#type' => 'textfield',
    '#title' => t('WWW'),
    '#size' => 30,
    '#default_value' => isset($node->www) ? $node->www : '',
  );

  $form['group4'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group4') : -17,
  );

  $form['group4']['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
    '#size' => 30,
    '#default_value' => isset($node->phone) ? $node->phone : '',
  );

  $form['group4']['im'] = array(
    '#type' => 'textfield',
    '#title' => t('IM'),
    '#size' => 30,
    '#default_value' => isset($node->im) ? $node->im : '',
  );

  //Check to see if the body field is still there, if so, display it.
  $body = field_get_items('stormperson',$node,'body');
  if($body) {
    $form['body_field'] = $body;
  }

  $form['title_old'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($node->title_old) ? $node->title_old : NULL,
  );

  return $form;
}

function stormperson_validate($node, &$form) {
  if (!empty($node->user_name)) {
    $username = $node->user_name;
    $ass_user = user_load_by_name($username);
    if (!empty($ass_user)) {
      $query = db_select('node', 'n');

      $query->fields('n', array('nid', 'title'))
            ->condition('stp.user_uid', $ass_user->uid)
            ->join('stormperson', 'stp', 'n.nid = stp.nid');

      $row = $query->execute()->fetchAssoc();
        if ($row && (empty($form['#node']->user_name) || ($form['#node']->user_name != $node->user_name))) {
          $message = t('This Drupal user is already assigned to a Storm person (!link). The same Drupal user can not be assigned to two Storm people.', array('!link' => l($row['title'], 'node/'. $row['nid'])));
        form_set_error('user_name', $message);
      }
    }
  }
}

function stormperson_user_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $query = db_select('users', 'u')
      ->fields('u', array('name', 'uid'))
      ->condition('name', db_like($string) . '%', 'LIKE');

    $subquery = db_select('stormperson', 'stp');
    $subquery->addField('stp', 'user_uid', 'uid');

    $query->condition('uid', $subquery, 'NOT IN');
    $result = $query->execute();

    foreach($result as $row) {
      $matches[$row->name] = check_plain($row->name);
    }
    drupal_json_output($matches);
  }
}

function stormperson_insert($node) {
  _stormperson_beforesave($node);

  db_insert('stormperson')
    ->fields(array(
      'vid' => $node->vid,
      'nid' => $node->nid,
      'organization_nid' => $node->organization_nid,
      'organization_title' => $node->organization_title,
      'prefix' => $node->prefix,
      'email' => $node->email,
      'www' => $node->www,
      'phone' => $node->phone,
      'im' => $node->im,
      'user_uid' => $node->user_uid,
    ))
    ->execute();

  _stormperson_aftersave($node);
}

function stormperson_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    stormperson_insert($node);
  }
  else {
    _stormperson_beforesave($node);

    db_update('stormperson')
      ->fields(array(
        'organization_nid' => $node->organization_nid,
        'organization_title' => $node->organization_title,
        'prefix' => $node->prefix,
        'email' => $node->email,
        'www' => $node->www,
        'phone' => $node->phone,
        'im' => $node->im,
        'user_uid' => $node->user_uid,
      ))
      ->condition('vid', $node->vid)
      ->execute();

    _stormperson_aftersave($node);

    if ($node->title != $node->title_old) {
      module_invoke_all('stormperson_change', $node->nid, $node->title);
    }
  }
}

function _stormperson_beforesave(&$node) {
  $username = $node->user_name;
  $ass_user = user_load_by_name($username);
  $node->user_uid = $ass_user->uid;
  if (!$node->email) {
    $node->email = $ass_user->mail;
  }

  $query = db_select('node', 'n');
  $query->join('stormorganization', 'sor', 'sor.vid = n.vid');
  $result = $query
    ->fields('n', array('title'))
    ->condition('n.type', 'stormorganization')
    ->condition('n.nid', $node->organization_nid)
    ->execute();

  $record = $result->fetchAssoc();

  $node->organization_title = $record['title'];
}

function _stormperson_aftersave(&$node) {
  global $user;
  if ($user->uid == $node->user_uid) {
    $user->stormperson_nid = $node->nid;
    $user->stormorganization_nid = $node->organization_nid;
  }
}

function stormperson_node_revision_delete($node) {
  // Notice that we're matching a single revision based on the node's vid.
  db_delete('stormperson')
    ->condition('vid', $node->vid)
    ->execute();
}

function stormperson_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_delete('stormperson')
    ->condition('nid', $node->nid)
    ->execute();

  global $user;
  if ($user->uid == $node->user_uid) {
    $user->stormperson_nid = -1;
    $user->stormorganization_nid = -1;
  }
}

function stormperson_load($nodes) {
  foreach ($nodes as $nid => &$node) {
    $result = db_select('stormperson', 'spe')
      ->fields('spe')
      ->condition('spe.vid', $node->vid)
      ->execute();
    $record = $result->fetchAssoc();

    foreach ($record as $key => $value) {
      $node->$key = $value;
    }

    $ass_user = user_load($node->user_uid);
    $node->user_name = $ass_user->name;
    $node->title_old = $node->title;
  }
}

function stormperson_view($node, $view_mode) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Storm'), 'storm');
  $breadcrumb[] = l(t('People'), 'storm/people');
  drupal_set_breadcrumb($breadcrumb);

  return theme('stormperson_view', array('node' => $node, 'view_mode' => $view_mode));
}

function _stormperson_people_access($node=NULL) {
  if ($node == NULL) return FALSE;
  if ($node->type == 'stormorganization') return TRUE;
  return FALSE;
}

function stormperson_user($type, &$edit, &$account, $category = NULL) {
  switch ($type) {
    case 'load':
      return _stormperson_user_load($account);
    case 'delete':
      return _stormperson_user_delete($account);
  }
}

function _stormperson_user_load(&$account) {
  static $loaded_persons = array();
  if (isset($loaded_persons[$account->uid])) {
    if (is_object($loaded_persons[$account->uid])) {
      $account->stormperson_nid = $loaded_persons[$account->uid]->nid;
      $account->stormorganization_nid = $loaded_persons[$account->uid]->organization_nid;
    }
  }
  else {
    $result = db_query("SELECT nid, organization_nid FROM {stormperson} WHERE user_uid=:uid", array(':uid' => $account->uid));
    $a = $result->fetchObject();
    if ($a) {
      $loaded_persons[$account->uid] = new stdClass();
      $loaded_persons[$account->uid]->nid = $a->nid;
      $loaded_persons[$account->uid]->organization_nid = $a->organization_nid;
      $account->stormperson_nid = $loaded_persons[$account->uid]->nid;
      $account->stormorganization_nid = $loaded_persons[$account->uid]->organization_nid;
    }
    else {
      $loaded_persons[$account->uid] = 0;
    }
  }
}

function _stormperson_user_delete(&$account) {
  db_query("UPDATE {stormperson} SET user_uid=NULL WHERE user_uid=%d", $account->uid);
}

function stormperson_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'stormperson'),
  );
}

/**
 * @function
 * A helper function to return the email address of a stormperson
 */
function stormperson_primary_email($node) {
  if ($node->type !== 'stormperson') {
    return NULL;
  }
  // If there is a Drupal user account use that email
  if ($node->user_uid) {
    $stormperson_person = user_load($node->user_uid);
    return $stormperson_person->mail;
  }
  // Else use the stormperson email
  elseif ($node->email) {
    return $node->email;
  }
}

function stormperson_storm_dashboard_links($type) {
  $links = array();
  if ($type == 'page' || $type == 'block') {
    $links[] = array(
      'theme' => 'storm_dashboard_link',
      'title' => t('People'),
      'icon' => 'stormpeople',
      'path' => 'storm/people',
      'params' => array(),
      'access_arguments' => 'Storm person: access',
      'node_type' => 'stormperson',
      'add_type' => 'stormperson',
      'map' => array(),
      'weight' => 2,
    );
  }
  return $links;
}
