<?php

/**
 * @file
 * Functionality for the Storm Team module
 * Organized into the following sections:
 * - General hooks: (help), menu, perm, theme, views_api
 * - Node specific hooks: node_info, content_extra_fields, access, access_sql,
 *     storm_rewrite_where_sql, form, load, view, _beforesave, insert, update,
 *     delete, nodeapi
 */

/**
 * @function
 * Implementation of hook_permission().
 */
function stormteam_permission() {
  return array(
    'Storm team: access' => array(
      'title' => t('Access Storm Team lists'),
    ),
    'Storm team: add' => array(
      'title' => t('Add Storm Teams'),
    ),
    'Storm team: view all' => array(
      'title' => t('View Any Storm Team'),
    ),
    'Storm team: view own' => array(
      'title' => t('View Authored Storm Team'),
    ),
    'Storm team: view belonged' => array(
      'title' => t('View Storm Team if belonged to'),
    ),
    'Storm team: edit all' => array(
      'title' => t('Edit Any Storm Team'),
    ),
    'Storm team: edit own' => array(
      'title' => t('Edit Authored Storm Team'),
    ),
    'Storm team: edit belonged' => array(
      'title' => t('Edit Storm Team if belonged to'),
    ),
    'Storm team: delete all' => array(
      'title' => t('Edit Any Storm Team'),
    ),
    'Storm team: delete own' => array(
      'title' => t('Delete Authored Storm Team'),
    ),
    'Storm team: delete belonged' => array(
      'title' => t('Delete Storm Team if belonged to'),
    ),
  );
}

/**
 * @function
 * Implementation of hook_theme().
 */
function stormteam_theme() {
  return array(
    'stormteam_view' => array(
      'file'      => 'stormteam.theme.inc',
      'variables' => array('node', 'view_mode'),
    ),
  );
}

/**
 * @function
 * Implementation of hook_views_api().
 */
function stormteam_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'stormteam'),
  );
}

/**
 * @function
 * Implementation of hook_node_info().
 */
function stormteam_node_info() {
  return array(
    'stormteam' => array(
      'name' => t('Team'),
      'base' => 'stormteam',
      'description' => t('A team for use within the Storm project management application'),
      'title_label' => t('Team Name'),
      'body_label' => t('Description'),
    )
  );
}

/**
 * @function
 * Implementation of hook_content_extra_fields().
 */
function stormteam_content_extra_fields($type_name) {
  if ($type_name == 'stormteam') {
    return array(
      'group1' => array('label' => 'Team members', 'weight' => -20),
    );
  }
}

/**
 * @function
 * Implementation of hook_access().
 */
function stormteam_access($op, $node, $account = NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  if (is_numeric($node)) $node = node_load($node);

  switch ($op) {
    case 'create':
      return user_access('Storm team: add');
    case 'view':
      if (user_access('Storm team: view all')) {
        return TRUE;
      }
      elseif (user_access('Storm team: view own') && ($account->uid == $node->uid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: view belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormperson_nid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: view belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormorganization_nid)) {
        return TRUE;
      }
      break;
    case 'update':
      if (user_access('Storm team: edit all')) {
        return TRUE;
      }
      elseif (user_access('Storm team: edit own') && ($account->uid == $node->uid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: edit belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormperson_nid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: edit belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormorganization_nid)) {
        return TRUE;
      }
      break;
    case 'delete':
      if (user_access('Storm team: delete all')) {
        return TRUE;
      }
      elseif (user_access('Storm team: delete own') && ($account->uid == $node->uid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: delete belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormperson_nid)) {
        return TRUE;
      }
      elseif (user_access('Storm team: delete belonged') && stormteam_user_belongs_to_team($node->nid, $account->stormorganization_nid)) {
        return TRUE;
      }
      break;
  }
  return FALSE;
}

/**
 * @function
 * Function to add node access rules onto database queries
 */
function stormteam_access_sql($sql, $where = array()) {
  if (user_access('Storm team: view all')) {
    $where[] = "'storm_access'='storm_access'";
    return storm_rewrite_sql($sql, $where);
  }

  global $user;

  $cond = '';
  if (user_access('Storm team: view own')) {
    $cond .= 'n.uid='. $user->uid;
  }
  if (user_access('Storm team: view belonged')) {
    if (!empty($cond)) $cond .= ' OR ';
    $cond .= "ste.mnid =  ". $user->stormperson_nid;
  }
  if (empty($cond)) $cond = '0=1';
  $where[] = $cond;

  $where[] = "'storm_access'='storm_access'";
  return storm_rewrite_sql($sql, $where);
}

/**
 * @function
 * Implementation of hook_storm_rewrite_where_sql().
 */
function stormteam_storm_rewrite_where_sql($query, $primary_table, $account) {
  static $conds = array();

  if (isset($conds[$primary_table][$account->uid])) {
    return $conds[$primary_table][$account->uid];
  }

  if (preg_match("/'storm_access'='storm_access'/", $query)) {
    $cond = '';
  }
  else {
    if (user_access('Storm team: view all', $account)) {
      return '';
    }

    $cond = '';
    if (user_access('Storm team: view own', $account)) {
      $cond .= " ${primary_table}.uid=". $account->uid;

    }
    if (user_access('Storm team: view belonged', $account)) {
      if ($cond) {
        $cond .= ' OR ';
      }
      $cond .= "ste1.mnid = ". $account->stormperson_nid;
    }
    if ($cond) {
      $cond = " WHEN 'stormteam' THEN (SELECT DISTINCT 1 FROM {stormteam} ste1 WHERE ste1.vid=${primary_table}.vid AND ($cond)) ";
    }
    else {
      $cond = " WHEN 'stormteam' THEN 0 ";
    }
  }

  $conds[$primary_table][$account->uid] = $cond;
  return $cond;
}

/**
 * @function
 * Implementation of hook_form().
 */
function stormteam_form(&$node) {
  $breadcrumb = array(
    l(t('Storm'), 'storm'),
    l(t('Teams'), 'storm/teams'),
  );
  drupal_set_breadcrumb($breadcrumb);

  $type = node_type_get_type($node);

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'title') : -21,
  );

  $form['group1'] = array(
    '#type' => 'markup',
    '#weight' => module_exists('content') ? content_extra_field_weight($node->type, 'group1') : -20,
  );

  $options = array(0 => '-');

  $per_query = db_select('node', 'n');
  $per_query->join('stormperson', 'spe', 'n.vid = spe.vid');
  $per_result = $per_query
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'stormperson')
    ->condition('n.status', 1)
    ->orderBy('n.title', 'ASC')
    ->execute();

//  $s_per = stormperson_access_sql($s_per);
//  $s_per = db_rewrite_sql($s_per);
  $people = array();
  foreach ($per_result as $person) {
    $people[$person->nid] = $person->title;
  }

  $options = $options + array(-1 => t('-PEOPLE-')) + $people;

  $org_result = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'stormorganization')
    ->condition('n.status', 1)
    ->orderBy('n.title', 'ASC')
    ->execute();

//  $s_org = stormorganization_access_sql($s_org);
//  $s_org = db_rewrite_sql($s_org);
  $organizations = array();
  foreach ($org_result as $organization) {
    $organizations[$organization->nid] = $organization->title;
  }

  $options = $options + array(-2 => t('-ORGANIZATIONS-')) + $organizations;

  $i = 1;
  $variable = 'members_array_'. $i;

  // Add rows for existing team members
  if (isset($node->members_array) && is_array($node->members_array)) {
    foreach ($node->members_array as $node->$variable => $name) {
      $form['group1'][$variable] = array(
        '#type' => 'select',
        '#title' => t('Team Member @num', array('@num' => $i)),
        '#options' => $options,
        '#default_value' => $node->$variable,
      );
      $i++;
      $variable = 'members_array_'. $i;
    }
  }

  // Add placeholder rows
  for ($j = 0; $j < 3; $j++) {
    $variable = 'members_array_'. $i;
    $form['group1'][$variable] = array(
      '#type' => 'select',
      '#title' => t('Team Member @num', array('@num' => $i)),
      '#options' => $options,
      '#default_value' => (isset($node->$variable)) ? $node->$variable : NULL,
    );
    $i++;
  }

  $body = field_get_items('stormteam',$node,'body');
  if($body) {
    $form['body_field'] = $body;
  }

  $form['title_old'] = array(
    '#type' => 'hidden',
    '#default_value' => (isset($node->title_old)) ? $node->title_old : NULL,
  );

  return $form;
}

/**
 * @function
 * Implementation of hook_load().
 */
function stormteam_load($nodes) {
  foreach ($nodes as $nid => &$node) {
    $team_query = db_select('node', 'n');
    $team_query->join('stormteam', 'ste', 'n.nid = ste.mnid');
    $team_result = $team_query
      ->fields('n', array('title', 'status'))
      ->fields('ste', array('mnid'))
      ->condition('ste.vid', $node->vid)
      ->execute();

    $node->members_array = array();
    $node->members_deactivated_array = array();
    foreach ($team_result as $members) {
      $node->members_array[$members->mnid] = $members->title;
      if ($members->status == 0) {
        $node->members_deactivated_array[$members->mnid] = $members->title;
      }
    }
    $node->title_old = $node->title;
  }
}

/**
 * @function
 * Implementation of hook_view().
 */
function stormteam_view($node, $view_mode) {
  $breadcrumb = array(
    l(t('Storm'), 'storm'),
    l(t('Teams'), 'storm/teams'),
  );
  drupal_set_breadcrumb($breadcrumb);

  return theme('stormteam_view', array('node' => $node, 'view_mode' => $view_mode));
}

/**
 * @function
 * Function to be called internally before saving Storm Team nodes
 */
function _stormteam_beforesave(&$node) {
  $i = 1;
  $variable = 'members_array_'. $i;

  while (isset($node->$variable)) {
    $per_result = db_select('node', 'n')
      ->fields('n', array('title'))
      ->condition('n.nid', $node->$variable)
      ->execute();

    $title = $per_result->fetchObject();
    if (!empty($title)) {
      $node->members_array[$node->$variable] = $title->title;
    }
    $i++;
    $variable = 'members_array_'. $i;
  }
  if (isset($node->members_array)) {
    if (array_key_exists(0, $node->members_array)) {
      unset($node->members_array[0]);
    }

    $node->members = serialize($node->members_array);
  }
}

/**
 * @function
 * Implementation of hook_insert().
 */
function stormteam_insert($node) {
  _stormteam_beforesave($node);
  if (isset($node->vid) && (isset($node->nid)) && (isset($node->members_array))) {
    $member = new stdClass();
    $member->nid = $node->nid;
    $member->vid = $node->vid;
    foreach ($node->members_array as $mnid => $member_name) {
      $member->mnid = $mnid;
      drupal_write_record('stormteam', $member);
    }
  }
}

/**
 * @function
 * Implementation of hook_update().
 */
function stormteam_update($node) {
  _stormteam_beforesave($node);

  if ($node->revision) {
    stormteam_insert($node);
  }
  else {

    if (isset($node->vid) && (isset($node->nid)) && (isset($node->members_array))) {
      // Delete the old members
      db_delete('stormteam')
        ->condition('vid', $node->vid)
        ->execute();

      // Insert entries
      $member = new stdClass();
      $member->nid = $node->nid;
      $member->vid = $node->vid;
      foreach ($node->members_array as $mnid => $member_name) {
        $member->mnid = $mnid;
        drupal_write_record('stormteam', $member);
      }
    }

    // Invokes hook_stormteam_change so that if title has changed, other modules that have cached the title can update it.
    if ($node->title != $node->title_old) {
      module_invoke_all('stormteam_change', $node->nid, $node->title);
    }
  }
}

/**
 * @function
 * Implementation of hook_delete().
 */
function stormteam_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_delete('stormteam')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * @function
 * Implementation of hook_nodeapi().
 */
function stormteam_node_revision_delete($node) {
  // Notice that we're matching a single revision based on the node's vid.
  db_delete('stormorganization')
    ->condition('vid', $node->vid)
    ->execute();
}

/**
 * @function
 * Function to return an autocomplete list for Storm Teams
 */
function stormteam_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $s = "SELECT title FROM {node} AS n WHERE n.type='stormteam' AND LOWER(title) LIKE LOWER('%%%s%%')";
    $s = stormteam_access_sql($s);
    $s = db_rewrite_sql($s);

    $result = db_query_range($s, $string, 0, 10);
    while ($team = db_fetch_object($result)) {
      $matches[$team->title] = check_plain($team->title);
    }
  }

  drupal_json($matches);
}

/**
 * @function
 * Function to return an autocomplete list for Storm Teams and People
 */
function stormteam_autocomplete_combo($string = '') {
  $matches = array();
  if ($string) {
    // TO BE COMPLETED
    $s = "SELECT title FROM {node} AS n WHERE n.type='stormteam' AND LOWER(title) LIKE LOWER('%s%%')";
    $s = stormteam_access_sql($s);
    $s = db_rewrite_sql($s);

    $result = db_query_range($s, $string, 0, 10);
    while ($obj = db_fetch_object($result)) {
      $matches[$obj->title] = check_plain($obj->title);
    }
  }

  drupal_json($matches);
}

/**
 * @function
 * Returns whether user is in a Storm team based on team $node and user $account
 */
function stormteam_user_belongs_to_team($team, $person_or_organization_nid) {
  $node = node_load($team);

  // Check for person_or_organization_nid in the team members array and return TRUE / FALSE
  if (is_array($node->members_array)) {
    return array_key_exists($person_or_organization_nid, $node->members_array);
  }
  else {
    return FALSE;
  }
}

/**
 * @function
 * Function to return the teams that a user is a member of
 */
function stormteam_user_return_teams($account = NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  // Get the list of team nodes. Include organizations which the person is a member of.
  $s = "SELECT ste.nid FROM {stormteam} ste JOIN {stormperson} stp ON (stp.nid = ste.mnid OR stp.organization_nid = ste.mnid) WHERE stp.user_uid = %d";
  $r = db_query($s, $account->uid);
  $teams = array();
  while ($team = db_fetch_object($r)) {
    $teams[] = $team->nid;
  }

  return $teams;
}

function stormteam_storm_dashboard_links($type) {
  $links = array();
  if ($type == 'page' || $type == 'block') {
    $links[] = array(
      'theme' => 'storm_dashboard_link',
      'title' => t('Teams'),
      'icon' => 'stormteams',
      'path' => 'storm/teams',
      'params' => array(),
      'access_arguments' => 'Storm team: access',
      'node_type' => 'stormteam',
      'add_type' => 'stormteam',
      'map' => array(),
      'weight' => 3,
    );
  }
  return $links;
}
