<?php
// $Id$

/**
 * @file
 * Functions to implement a dashboard for Storm.
 * The Storm dashboard gives easy access to all parts of Storm.
 */

 /**
  * @function
  * Implementation of hook_menu
  */
function stormdashboard_menu() {
  $items = array();
  
  $items['storm'] = array(
    'title' => t('Storm'),
    'description' => t('Storm Dashboard'),
    'page callback' => 'storm_dashboard',
    'access arguments' => array('Storm: access dashboard'),
    'parent' => '',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * @function
 * Implementation of hook_permission
 */
function stormdashboard_permission() {
  return array(
    'Storm: access dashboard' => array(
      'title' => t('Storm: access dashboard'),
      'description' => t('View Storm dashboard'),
    ),
  );
}

/**
 * @function
 * Implementation of hook_theme
 */
function stormdashboard_theme() {
  return array(
    'stormdashboard_dashboard' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * @function
 * Function to create dashboard (call to theme function)
 */
function stormdashboard_dashboard() {
  drupal_set_title(t('Storm Dashboard'));
  return theme('stormdashboard_dashboard');
}